# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build-arm64
      run: GOOS=android GOARCH=arm64 CGO_ENABLED=0 go build -o build/go-tsu -v -ldflags="-X 'github.com/nteditor/go-tsu/cmd.BuildType=github-action-(${{ github.run_id }})'"

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: v${{ github.event.inputs.version }}
        files: |
          ./build/go-tsu
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
